Implementation of filters on the Activities page
As-Raparigas-do-Codigo/ardc-website pull request #212
Opened 2024-07-03 16:53 UTC by msantosdevlab

### Descrição

Foram inseridos os filtros das tags na página Atividades
Fixes #210 

### Como testar esta modificação?

https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/89532722/7187e794-e39a-4e8d-b6d2-2aeb669828f2

### Checklist:

- [x] O meu PR segue as regras de estilo de código deste projeto
- [x] Eu fiz uma autoavaliação (review) do meu próprio código ou materiais
- [x] Eu fiz as alterações correspondentes na documentação

2024-07-05 09:56 UTC, toothlesspanda requested changes, later dismissed

2024-07-05 09:56 UTC, toothlesspanda commented on src/pages/Activities/index.js
> +        </button>
isto pode ser feito por um array, evitando a duplicacao de código

```javascript
const calculateCategoryTotal = (category) =>{
   return activitiesRefined && activitiesRefined.filter((item) => item.category.label === category).length;
}

(...)

<button onClick={() => handleCategoryClick('')} className={`${selectedCategory === '' ? 'activeTab' : 'inactiveTab'} rounded-pill`}> Todos <span>{activitiesRefined && activitiesRefined.length;}</span> </button>
Constants.Categories.map((item) =>{
        <button onClick={() => handleCategoryClick('evento')} className={`${selectedCategory === item.label ? 'activeTab' : 'inactiveTab'} rounded-pill`}> { capitalize(item.label)} <span> { calculateCategoryTotal(item.label)  }</span>
        </button>
})


//utils.js
function capitalize(word) {
   return word.charAt(0).toUpperCase() + word.slice(1);
}

```

que achas?

2024-07-05 09:56 UTC, toothlesspanda commented on src/pages/Activities/activities.scss
> +}
podes substituir as cores pelas variáveis que estao no ./styles/variables.scss ? 
para que possa ficar consistente com as cores do sistema, caso queiramos mudar

2024-07-09 20:57 UTC, toothlesspanda commented on src/pages/Activities/index.js
> +  const categories = Array.from(new Set(activities.map(item => item.category.label)));
Acho que não precisas disto, podes simplesmente fazer require das constantes, já existe uma lista declarada com as categorias todas. Que achas?

2024-07-09 20:57 UTC, toothlesspanda commented on src/pages/Activities/index.js
> +        ))}
Also, poderíamos ter antes uma dropdown com seleção múltipla, mas isto pode ser uma iteração para depois

2024-07-09 21:10 UTC, isabelcosta commented on src/pages/Activities/index.js
> +        ))}
Acho que pode ser para depois também, Não sei se temos design para esta interação 🤔 podia também ser uma outra issue.

2024-07-13 09:51 UTC, isabelcosta approved these changes
Obrigada pela tua contribuição @msantosdevlab !
Muito bom trabalho! 👏🏾 💯

2024-07-13 09:53 UTC, merged